version: '3.1'
services:
  db:
    environment:
      - POSTGRES_PORT=5432
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - ${POSTGRES_PORT}:5432
